GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Traceback (most recent call last):
  File "/data/rradev/generator_reweight/train.py", line 97, in <module>
    trainer.fit(model, data)
  File "/afs/cern.ch/user/r/rradev/envs/generator_translation/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/afs/cern.ch/user/r/rradev/envs/generator_translation/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/afs/cern.ch/user/r/rradev/envs/generator_translation/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/afs/cern.ch/user/r/rradev/envs/generator_translation/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1105, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/afs/cern.ch/user/r/rradev/envs/generator_translation/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1447, in _call_setup_hook
    self._call_lightning_datamodule_hook("setup", stage=fn)
  File "/afs/cern.ch/user/r/rradev/envs/generator_translation/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1569, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/data/rradev/generator_reweight/train.py", line 35, in setup
    self.val_dataset = ParticleCloud(
  File "/data/rradev/generator_reweight/src/root_dataloader.py", line 118, in __init__
    self.data, self.labels = self.load_data()
  File "/data/rradev/generator_reweight/src/root_dataloader.py", line 162, in load_data
    dataset_a, labels_a = self.load_generator(self.generator_a)
  File "/data/rradev/generator_reweight/src/root_dataloader.py", line 140, in load_generator
    w = data['W'].array(library='np')
  File "/afs/cern.ch/user/r/rradev/envs/generator_translation/lib/python3.10/site-packages/awkward/highlevel.py", line 1123, in __getattr__
    raise AttributeError(
AttributeError: no field named 'array'
(https://github.com/scikit-hep/awkward-1.0/blob/1.8.0/src/awkward/highlevel.py#L1124)
/eos/user/r/rradev/new_parquet/test_file_flat_argon_12_GENIEv2_7.parquet